@startuml
hide circle
rectangle "sample-service" as sample-service {
    rectangle "infra" as sample-service/infra {
        rectangle "BigQuery" as sample-service/infra/BigQuery {
            rectangle "movie" as sample-service/infra/BigQuery/movie {
                class "movies" as sample-service/infra/BigQuery/movie/movies {
                    PARTITIONEDテーブル\n【スキーマ】\nid: string REQUIRED\nname: string REQUIRED\nimage_url: string REQUIRED\ndescription: string REQUIRED 
                }
                class "talent_relation_scores" as sample-service/infra/BigQuery/movie/talent_relation_scores {
                    各タレントとの関連度のスコアを保持するテーブル\nPARTITIONEDテーブル\n\n【スキーマ】\nmovie/id: string REQUIRED\ntalent_id: string REQUIRED\nscore: float REQUIRED
                }
            }
        }
        rectangle "CloudSQL" as sample-service/infra/CloudSQL {
            rectangle "movie-service" as sample-service/infra/CloudSQL/movie-service {
                class "movies" as sample-service/infra/CloudSQL/movie-service/movies {
                    【スキーマ】\nid: string PRIMARY_KEY\nname: string NOT_NULL\nimage_url: string NOT_NULL\ndescription: string NOT_NULL 
                }
                class "movie_talents" as sample-service/infra/CloudSQL/movie-service/movie_talents {
                    【スキーマ】\nmovie/id: string PRIMARY_KEY\ntalent_id: string PRIMARY_KEY
                }
            }
            rectangle "talent-service" as sample-service/infra/CloudSQL/talent-service {
                class "talents" as sample-service/infra/CloudSQL/talent-service/talents {
                    【スキーマ】\nid: string PRIMARY_KEY\nname: string NOT_NULL\nimage_url: string NOT_NULL\ndescription: string NOT_NULL 
                }
            }
        }
    }
    rectangle "internet" as sample-service/internet {
        circle "movie_media_A" as sample-service/internet/movie_media_A
        circle "movie_media_B" as sample-service/internet/movie_media_B
    }
    rectangle "repository" as sample-service/repository {
        rectangle "workflows" as sample-service/repository/workflows {
            rectangle "scrape-and-load-movies" as sample-service/repository/workflows/scrape-and-load-movies {
                note "schedule: 0,30 * * * *" as sample_service_repository_workflows_scrape_and_load_movies_note
                rectangle "scrape-movies-media-b" as sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-b {
                    rectangle "ref(sample-service/repository/movie-service/batch/scrape-movies)" as sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-b/sample-service/repository/movie-service/batch/scrape-movies {
                        circle "1_各メディアをスクレイプする" as sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-b/sample-service/repository/movie-service/batch/scrape-movies/1_各メディアをスクレイプする
                        circle "2_BQに保存する" as sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-b/sample-service/repository/movie-service/batch/scrape-movies/2_BQに保存する
                    }
                }
                circle "start" as sample-service/repository/workflows/scrape-and-load-movies/start
                rectangle "calc-talent-relation-score" as sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score {
                    rectangle "ref(sample-service/repository/movie-service/batch/calc-talent-relation-score)" as sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score {
                        circle "1_タレントを取得する" as sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/1_タレントを取得する
                        circle "2_計算対象の記事を取得する" as sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/2_計算対象の記事を取得する
                        circle "3_関連度のスコアを計算する" as sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/3_関連度のスコアを計算する
                        circle "4_関連度のスコアを保存する" as sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/4_関連度のスコアを保存する
                    }
                }
                circle "end" as sample-service/repository/workflows/scrape-and-load-movies/end
                rectangle "load-movies" as sample-service/repository/workflows/scrape-and-load-movies/load-movies {
                    rectangle "ref(sample-service/repository/movie-service/batch/load-movies)" as sample-service/repository/workflows/scrape-and-load-movies/load-movies/sample-service/repository/movie-service/batch/load-movies {
                        circle "1_関連度が閾値を超える映画を取得" as sample-service/repository/workflows/scrape-and-load-movies/load-movies/sample-service/repository/movie-service/batch/load-movies/1_関連度が閾値を超える映画を取得
                        circle "2_映画を保存する" as sample-service/repository/workflows/scrape-and-load-movies/load-movies/sample-service/repository/movie-service/batch/load-movies/2_映画を保存する
                    }
                }
                rectangle "scrape-movies-media-a" as sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-a {
                    rectangle "ref(sample-service/repository/movie-service/batch/scrape-movies)" as sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-a/sample-service/repository/movie-service/batch/scrape-movies {
                        circle "1_各メディアをスクレイプする" as sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-a/sample-service/repository/movie-service/batch/scrape-movies/1_各メディアをスクレイプする
                        circle "2_BQに保存する" as sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-a/sample-service/repository/movie-service/batch/scrape-movies/2_BQに保存する
                    }
                }
            }
        }
        rectangle "talent-service" as sample-service/repository/talent-service {
            rectangle "internal-api" as sample-service/repository/talent-service/internal-api {
                class "タレント取得API" as sample-service/repository/talent-service/internal-api/タレント取得API {
                    GET /internal/api/v1/talents\n\n【リクエスト】\n{\n  cursor: string,nullable,取得した最後のtalent_id\n  limit: int,取得したいtalent数\n}\n\n【レスポンス】\n200: {\n  talents: [{\n    id: string\n    name: string\n    image_url: string\n    description: string\n  }]\n}\n401: {\n  error_code: string\n}
                }
            }
        }
    }
}
"sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-b/sample-service/repository/movie-service/batch/scrape-movies/1_各メディアをスクレイプする" --> "sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-b/sample-service/repository/movie-service/batch/scrape-movies/2_BQに保存する"
"sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-b/sample-service/repository/movie-service/batch/scrape-movies/1_各メディアをスクレイプする" ..|> "sample-service/internet/movie_media_A"
"sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-b/sample-service/repository/movie-service/batch/scrape-movies/1_各メディアをスクレイプする" ..|> "sample-service/internet/movie_media_B"
"sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-b/sample-service/repository/movie-service/batch/scrape-movies/2_BQに保存する" --|> "sample-service/infra/BigQuery/movie/movies"
"sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-b" --> "sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score"
"sample-service/repository/workflows/scrape-and-load-movies/start" --> "sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-a"
"sample-service/repository/workflows/scrape-and-load-movies/start" --> "sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-b"
"sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/1_タレントを取得する" --> "sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/2_計算対象の記事を取得する"
"sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/1_タレントを取得する" ..|> "sample-service/repository/talent-service/internal-api/タレント取得API"
"sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/2_計算対象の記事を取得する" --> "sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/3_関連度のスコアを計算する"
"sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/2_計算対象の記事を取得する" ..|> "sample-service/infra/BigQuery/movie/movies"
"sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/3_関連度のスコアを計算する" --> "sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/4_関連度のスコアを保存する"
"sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score/sample-service/repository/movie-service/batch/calc-talent-relation-score/4_関連度のスコアを保存する" --|> "sample-service/infra/BigQuery/movie/talent_relation_scores"
"sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score" --> "sample-service/repository/workflows/scrape-and-load-movies/load-movies"
"sample-service/repository/workflows/scrape-and-load-movies/load-movies/sample-service/repository/movie-service/batch/load-movies/1_関連度が閾値を超える映画を取得" --> "sample-service/repository/workflows/scrape-and-load-movies/load-movies/sample-service/repository/movie-service/batch/load-movies/2_映画を保存する"
"sample-service/repository/workflows/scrape-and-load-movies/load-movies/sample-service/repository/movie-service/batch/load-movies/1_関連度が閾値を超える映画を取得" ..|> "sample-service/infra/BigQuery/movie/movies"
"sample-service/repository/workflows/scrape-and-load-movies/load-movies/sample-service/repository/movie-service/batch/load-movies/1_関連度が閾値を超える映画を取得" ..|> "sample-service/infra/BigQuery/movie/talent_relation_scores"
"sample-service/repository/workflows/scrape-and-load-movies/load-movies/sample-service/repository/movie-service/batch/load-movies/2_映画を保存する" --|> "sample-service/infra/CloudSQL/movie-service/movies"
"sample-service/repository/workflows/scrape-and-load-movies/load-movies/sample-service/repository/movie-service/batch/load-movies/2_映画を保存する" --|> "sample-service/infra/CloudSQL/movie-service/movie_talents"
"sample-service/repository/workflows/scrape-and-load-movies/load-movies" --> "sample-service/repository/workflows/scrape-and-load-movies/end"
"sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-a/sample-service/repository/movie-service/batch/scrape-movies/1_各メディアをスクレイプする" --> "sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-a/sample-service/repository/movie-service/batch/scrape-movies/2_BQに保存する"
"sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-a/sample-service/repository/movie-service/batch/scrape-movies/1_各メディアをスクレイプする" ..|> "sample-service/internet/movie_media_A"
"sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-a/sample-service/repository/movie-service/batch/scrape-movies/1_各メディアをスクレイプする" ..|> "sample-service/internet/movie_media_B"
"sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-a/sample-service/repository/movie-service/batch/scrape-movies/2_BQに保存する" --|> "sample-service/infra/BigQuery/movie/movies"
"sample-service/repository/workflows/scrape-and-load-movies/scrape-movies-media-a" --> "sample-service/repository/workflows/scrape-and-load-movies/calc-talent-relation-score"
"sample-service/repository/talent-service/internal-api/タレント取得API" ..|> "sample-service/infra/CloudSQL/talent-service/talents"
@enduml
