@startuml
hide circle
rectangle "sample-service" as sample-service {
    rectangle "infra" as sample-service/infra {
        rectangle "BigQuery" as sample-service/infra/BigQuery {
            rectangle "tv_show" as sample-service/infra/BigQuery/tv_show {
                class "talent_relation_scores" as sample-service/infra/BigQuery/tv_show/talent_relation_scores {
                    各タレントとの関連度のスコアを保持するテーブル\nPARTITIONEDテーブル\n\n【スキーマ】\ntv_show_id: string REQUIRED\ntalent_id: string REQUIRED\nscore: float REQUIRED
                }
                class "tv_shows" as sample-service/infra/BigQuery/tv_show/tv_shows {
                    PARTITIONEDテーブル\n【スキーマ】\nid: string REQUIRED\nname: string REQUIRED\nimage_url: string REQUIRED\ndescription: string REQUIRED \ntv_region: string REQUIRED
                }
            }
        }
        rectangle "CloudSQL" as sample-service/infra/CloudSQL {
            rectangle "talent-service" as sample-service/infra/CloudSQL/talent-service {
                class "talents" as sample-service/infra/CloudSQL/talent-service/talents {
                    【スキーマ】\nid: string PRIMARY_KEY\nname: string NOT_NULL\nimage_url: string NOT_NULL\ndescription: string NOT_NULL 
                }
            }
            rectangle "tv-show-service" as sample-service/infra/CloudSQL/tv-show-service {
                class "tv_show_talents" as sample-service/infra/CloudSQL/tv-show-service/tv_show_talents {
                    【スキーマ】\ntv_show_id: string PRIMARY_KEY\ntalent_id: string PRIMARY_KEY
                }
                class "tv_shows" as sample-service/infra/CloudSQL/tv-show-service/tv_shows {
                    【スキーマ】\nid: string PRIMARY_KEY\nname: string NOT_NULL\nimage_url: string NOT_NULL\ndescription: string NOT_NULL \nstart_at: timestamp NOT_NULL \nend_at: timestamp NOT_NULL \ntv_region: string NOT_NULL 
                }
            }
        }
    }
    rectangle "internet" as sample-service/internet {
        circle "tv_show_media_A" as sample-service/internet/tv_show_media_A
        circle "tv_show_media_B" as sample-service/internet/tv_show_media_B
    }
    rectangle "repository" as sample-service/repository {
        rectangle "workflows" as sample-service/repository/workflows {
            rectangle "scrape-and-load-tv-shows" as sample-service/repository/workflows/scrape-and-load-tv-shows {
                note "schedule: 0,30 * * * *" as sample_service_repository_workflows_scrape_and_load_tv_shows_note
                rectangle "load-tv-shows" as sample-service/repository/workflows/scrape-and-load-tv-shows/load-tv-shows {
                    rectangle "ref(sample-service/repository/tv-show-service/batch/load-tv-shows)" as sample-service/repository/workflows/scrape-and-load-tv-shows/load-tv-shows/sample-service/repository/tv-show-service/batch/load-tv-shows {
                        circle "1_関連度が閾値を超える映画を取得" as sample-service/repository/workflows/scrape-and-load-tv-shows/load-tv-shows/sample-service/repository/tv-show-service/batch/load-tv-shows/1_関連度が閾値を超える映画を取得
                        circle "2_テレビ番組を保存する" as sample-service/repository/workflows/scrape-and-load-tv-shows/load-tv-shows/sample-service/repository/tv-show-service/batch/load-tv-shows/2_テレビ番組を保存する
                    }
                }
                rectangle "scrape-tv-shows-media-a" as sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-a {
                    rectangle "ref(sample-service/repository/tv-show-service/batch/scrape-tv-shows)" as sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-a/sample-service/repository/tv-show-service/batch/scrape-tv-shows {
                        circle "1_各メディアをスクレイプする" as sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-a/sample-service/repository/tv-show-service/batch/scrape-tv-shows/1_各メディアをスクレイプする
                        circle "2_BQに保存する" as sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-a/sample-service/repository/tv-show-service/batch/scrape-tv-shows/2_BQに保存する
                    }
                }
                rectangle "scrape-tv-shows-media-b" as sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-b {
                    rectangle "ref(sample-service/repository/tv-show-service/batch/scrape-tv-shows)" as sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-b/sample-service/repository/tv-show-service/batch/scrape-tv-shows {
                        circle "1_各メディアをスクレイプする" as sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-b/sample-service/repository/tv-show-service/batch/scrape-tv-shows/1_各メディアをスクレイプする
                        circle "2_BQに保存する" as sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-b/sample-service/repository/tv-show-service/batch/scrape-tv-shows/2_BQに保存する
                    }
                }
                circle "start" as sample-service/repository/workflows/scrape-and-load-tv-shows/start
                rectangle "calc-talent-relation-score" as sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score {
                    rectangle "ref(sample-service/repository/tv-show-service/batch/calc-talent-relation-score)" as sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score {
                        circle "2_計算対象の記事を取得する" as sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/2_計算対象の記事を取得する
                        circle "3_関連度のスコアを計算する" as sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/3_関連度のスコアを計算する
                        circle "4_関連度のスコアを保存する" as sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/4_関連度のスコアを保存する
                        circle "1_タレントを取得する" as sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/1_タレントを取得する
                    }
                }
                circle "end" as sample-service/repository/workflows/scrape-and-load-tv-shows/end
            }
        }
        rectangle "talent-service" as sample-service/repository/talent-service {
            rectangle "internal-api" as sample-service/repository/talent-service/internal-api {
                class "タレント取得API" as sample-service/repository/talent-service/internal-api/タレント取得API {
                    GET /internal/api/v1/talents\n\n【リクエスト】\n{\n  cursor: string,nullable,取得した最後のtalent_id\n  limit: int,取得したいtalent数\n}\n\n【レスポンス】\n200: {\n  talents: [{\n    id: string\n    name: string\n    image_url: string\n    description: string\n  }]\n}\n401: {\n  error_code: string\n}
                }
            }
        }
    }
}
"sample-service/repository/workflows/scrape-and-load-tv-shows/load-tv-shows/sample-service/repository/tv-show-service/batch/load-tv-shows/1_関連度が閾値を超える映画を取得" --> "sample-service/repository/workflows/scrape-and-load-tv-shows/load-tv-shows/sample-service/repository/tv-show-service/batch/load-tv-shows/2_テレビ番組を保存する"
"sample-service/repository/workflows/scrape-and-load-tv-shows/load-tv-shows/sample-service/repository/tv-show-service/batch/load-tv-shows/1_関連度が閾値を超える映画を取得" ..|> "sample-service/infra/BigQuery/tv_show/tv_shows"
"sample-service/repository/workflows/scrape-and-load-tv-shows/load-tv-shows/sample-service/repository/tv-show-service/batch/load-tv-shows/1_関連度が閾値を超える映画を取得" ..|> "sample-service/infra/BigQuery/tv_show/talent_relation_scores"
"sample-service/repository/workflows/scrape-and-load-tv-shows/load-tv-shows/sample-service/repository/tv-show-service/batch/load-tv-shows/2_テレビ番組を保存する" --|> "sample-service/infra/CloudSQL/tv-show-service/tv_shows"
"sample-service/repository/workflows/scrape-and-load-tv-shows/load-tv-shows/sample-service/repository/tv-show-service/batch/load-tv-shows/2_テレビ番組を保存する" --|> "sample-service/infra/CloudSQL/tv-show-service/tv_show_talents"
"sample-service/repository/workflows/scrape-and-load-tv-shows/load-tv-shows" --> "sample-service/repository/workflows/scrape-and-load-tv-shows/end"
"sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-a/sample-service/repository/tv-show-service/batch/scrape-tv-shows/1_各メディアをスクレイプする" --> "sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-a/sample-service/repository/tv-show-service/batch/scrape-tv-shows/2_BQに保存する"
"sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-a/sample-service/repository/tv-show-service/batch/scrape-tv-shows/1_各メディアをスクレイプする" ..|> "sample-service/internet/tv_show_media_A"
"sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-a/sample-service/repository/tv-show-service/batch/scrape-tv-shows/1_各メディアをスクレイプする" ..|> "sample-service/internet/tv_show_media_B"
"sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-a/sample-service/repository/tv-show-service/batch/scrape-tv-shows/2_BQに保存する" --|> "sample-service/infra/BigQuery/tv_show/tv_shows"
"sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-a" --> "sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score"
"sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-b/sample-service/repository/tv-show-service/batch/scrape-tv-shows/1_各メディアをスクレイプする" --> "sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-b/sample-service/repository/tv-show-service/batch/scrape-tv-shows/2_BQに保存する"
"sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-b/sample-service/repository/tv-show-service/batch/scrape-tv-shows/1_各メディアをスクレイプする" ..|> "sample-service/internet/tv_show_media_A"
"sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-b/sample-service/repository/tv-show-service/batch/scrape-tv-shows/1_各メディアをスクレイプする" ..|> "sample-service/internet/tv_show_media_B"
"sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-b/sample-service/repository/tv-show-service/batch/scrape-tv-shows/2_BQに保存する" --|> "sample-service/infra/BigQuery/tv_show/tv_shows"
"sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-b" --> "sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score"
"sample-service/repository/workflows/scrape-and-load-tv-shows/start" --> "sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-a"
"sample-service/repository/workflows/scrape-and-load-tv-shows/start" --> "sample-service/repository/workflows/scrape-and-load-tv-shows/scrape-tv-shows-media-b"
"sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/2_計算対象の記事を取得する" --> "sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/3_関連度のスコアを計算する"
"sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/2_計算対象の記事を取得する" ..|> "sample-service/infra/BigQuery/tv_show/tv_shows"
"sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/3_関連度のスコアを計算する" --> "sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/4_関連度のスコアを保存する"
"sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/4_関連度のスコアを保存する" --|> "sample-service/infra/BigQuery/tv_show/talent_relation_scores"
"sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/1_タレントを取得する" --> "sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/2_計算対象の記事を取得する"
"sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score/sample-service/repository/tv-show-service/batch/calc-talent-relation-score/1_タレントを取得する" ..|> "sample-service/repository/talent-service/internal-api/タレント取得API"
"sample-service/repository/workflows/scrape-and-load-tv-shows/calc-talent-relation-score" --> "sample-service/repository/workflows/scrape-and-load-tv-shows/load-tv-shows"
"sample-service/repository/talent-service/internal-api/タレント取得API" ..|> "sample-service/infra/CloudSQL/talent-service/talents"
@enduml
