@startuml
hide circle
rectangle "sample-service" as sample-service {
    rectangle "infra" as sample-service/infra {
        rectangle "BigQuery" as sample-service/infra/BigQuery {
            rectangle "tv_show" as sample-service/infra/BigQuery/tv_show {
                class "talent_relation_scores" as sample-service/infra/BigQuery/tv_show/talent_relation_scores {
                    各タレントとの関連度のスコアを保持するテーブル\nPARTITIONEDテーブル\n\n【スキーマ】\ntv_show_id: string REQUIRED\ntalent_id: string REQUIRED\nscore: float REQUIRED
                }
                class "tv_shows" as sample-service/infra/BigQuery/tv_show/tv_shows {
                    PARTITIONEDテーブル\n【スキーマ】\nid: string REQUIRED\nname: string REQUIRED\nimage_url: string REQUIRED\ndescription: string REQUIRED \ntv_region: string REQUIRED
                }
            }
        }
        rectangle "CloudSQL" as sample-service/infra/CloudSQL {
            rectangle "tv-show-service" as sample-service/infra/CloudSQL/tv-show-service {
                class "tv_show_talents" as sample-service/infra/CloudSQL/tv-show-service/tv_show_talents {
                    【スキーマ】\ntv_show_id: string PRIMARY_KEY\ntalent_id: string PRIMARY_KEY
                }
                class "tv_shows" as sample-service/infra/CloudSQL/tv-show-service/tv_shows {
                    【スキーマ】\nid: string PRIMARY_KEY\nname: string NOT_NULL\nimage_url: string NOT_NULL\ndescription: string NOT_NULL \nstart_at: timestamp NOT_NULL \nend_at: timestamp NOT_NULL \ntv_region: string NOT_NULL 
                }
            }
        }
    }
    rectangle "repository" as sample-service/repository {
        rectangle "tv-show-service" as sample-service/repository/tv-show-service {
            rectangle "batch" as sample-service/repository/tv-show-service/batch {
                rectangle "load-tv-shows" as sample-service/repository/tv-show-service/batch/load-tv-shows {
                    circle "1_関連度が閾値を超える映画を取得" as sample-service/repository/tv-show-service/batch/load-tv-shows/1_関連度が閾値を超える映画を取得
                    circle "2_テレビ番組を保存する" as sample-service/repository/tv-show-service/batch/load-tv-shows/2_テレビ番組を保存する
                }
            }
        }
    }
}
"sample-service/repository/tv-show-service/batch/load-tv-shows/1_関連度が閾値を超える映画を取得" --> "sample-service/repository/tv-show-service/batch/load-tv-shows/2_テレビ番組を保存する"
"sample-service/repository/tv-show-service/batch/load-tv-shows/1_関連度が閾値を超える映画を取得" ..|> "sample-service/infra/BigQuery/tv_show/tv_shows"
"sample-service/repository/tv-show-service/batch/load-tv-shows/1_関連度が閾値を超える映画を取得" ..|> "sample-service/infra/BigQuery/tv_show/talent_relation_scores"
"sample-service/repository/tv-show-service/batch/load-tv-shows/2_テレビ番組を保存する" --|> "sample-service/infra/CloudSQL/tv-show-service/tv_shows"
"sample-service/repository/tv-show-service/batch/load-tv-shows/2_テレビ番組を保存する" --|> "sample-service/infra/CloudSQL/tv-show-service/tv_show_talents"
@enduml
