@startuml
hide circle
rectangle "sample-service" as sample-service {
    rectangle "infra" as sample-service/infra {
        rectangle "BigQuery" as sample-service/infra/BigQuery {
            rectangle "tv_show" as sample-service/infra/BigQuery/tv_show {
                class "tv_shows" as sample-service/infra/BigQuery/tv_show/tv_shows {
                    PARTITIONEDテーブル\n【スキーマ】\nid: string REQUIRED\nname: string REQUIRED\nimage_url: string REQUIRED\ndescription: string REQUIRED \ntv_region: string REQUIRED
                }
            }
        }
    }
    rectangle "internet" as sample-service/internet {
        circle "tv_show_media_A" as sample-service/internet/tv_show_media_A
        circle "tv_show_media_B" as sample-service/internet/tv_show_media_B
    }
    rectangle "repository" as sample-service/repository {
        rectangle "tv-show-service" as sample-service/repository/tv-show-service {
            rectangle "batch" as sample-service/repository/tv-show-service/batch {
                rectangle "scrape-tv-shows" as sample-service/repository/tv-show-service/batch/scrape-tv-shows {
                    circle "1_各メディアをスクレイプする" as sample-service/repository/tv-show-service/batch/scrape-tv-shows/1_各メディアをスクレイプする
                    circle "2_BQに保存する" as sample-service/repository/tv-show-service/batch/scrape-tv-shows/2_BQに保存する
                }
            }
        }
    }
}
"sample-service/repository/tv-show-service/batch/scrape-tv-shows/1_各メディアをスクレイプする" --> "sample-service/repository/tv-show-service/batch/scrape-tv-shows/2_BQに保存する"
"sample-service/repository/tv-show-service/batch/scrape-tv-shows/1_各メディアをスクレイプする" ..|> "sample-service/internet/tv_show_media_A"
"sample-service/repository/tv-show-service/batch/scrape-tv-shows/1_各メディアをスクレイプする" ..|> "sample-service/internet/tv_show_media_B"
"sample-service/repository/tv-show-service/batch/scrape-tv-shows/2_BQに保存する" --|> "sample-service/infra/BigQuery/tv_show/tv_shows"
@enduml
