@startuml
hide circle
rectangle "sample-service" as sample-service {
    rectangle "infra" as sample-service/infra {
        rectangle "CloudSQL" as sample-service/infra/CloudSQL {
            rectangle "user-service" as sample-service/infra/CloudSQL/user-service {
                class "follows" as sample-service/infra/CloudSQL/user-service/follows {
                    【スキーマ】\nuser_id: string PRIMARY_KEY\ntalent_id: string PRIMARY_KEY
                }
            }
        }
    }
    rectangle "repository" as sample-service/repository {
        rectangle "user-service" as sample-service/repository/user-service {
            rectangle "external-api" as sample-service/repository/user-service/external-api {
                class "フォローAPI" as sample-service/repository/user-service/external-api/フォローAPI {
                    POST /api/v1/follow\n\n【リクエスト】\n{\n  talent_id: string\n}\n\n【レスポンス】\n204: {}\n401: {\n  error_code: string\n}
                }
            }
        }
    }
}
"sample-service/repository/user-service/external-api/フォローAPI" --|> "sample-service/infra/CloudSQL/user-service/follows"
@enduml
