@startuml
hide circle
rectangle "sample-service" as sample-service {
    rectangle "infra" as sample-service/infra {
        rectangle "CloudSQL" as sample-service/infra/CloudSQL {
            rectangle "user-service" as sample-service/infra/CloudSQL/user-service {
                class "users" as sample-service/infra/CloudSQL/user-service/users {
                    【スキーマ】\nid: string PRIMARY_KEY\nemail_address: string NOT_NULL\npassword_hash: string NOT_NULL\ncreated_at: timestamp NOT_NULL 
                }
            }
        }
    }
    rectangle "repository" as sample-service/repository {
        rectangle "user-service" as sample-service/repository/user-service {
            rectangle "external-api" as sample-service/repository/user-service/external-api {
                class "新規登録API" as sample-service/repository/user-service/external-api/新規登録API {
                    POST /api/v1/create_user\nユーザーを作成し、認証情報を保持するクッキーを返します\n\n【リクエスト】\n{\n  email: string\n  password: string\n}\n\n【レスポンス】\n204: {}\n400: {\n  error_code: string\n}
                }
            }
        }
    }
}
"sample-service/repository/user-service/external-api/新規登録API" --|> "sample-service/infra/CloudSQL/user-service/users"
@enduml
